'use client';
import {useState} from 'react';
import {Wallet,Leaf,MapPin,Sparkles,ArrowUpRight,ShoppingBasket,Bus,Utensils,CircleCheck,ChevronDown,Clock,SlidersHorizontal,Download,Check,Info} from 'lucide-react';
import {defaults,money,optimise,type Constraints} from '@/lib/planner';
const demo="I've got €45 until Friday. I live near DCU, need to go to college three days and need six dinners. I don't eat meat.";
type Result=ReturnType<typeof optimise>;
export default function Home(){
 const [c,setC]=useState<Constraints>(defaults),[message,setMessage]=useState(demo),[result,setResult]=useState<Result>(()=>optimise(defaults)),[selected,setSelected]=useState(0),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('basket'),[checked,setChecked]=useState<string[]>([]),[explanation,setExplanation]=useState(''),[dirty,setDirty]=useState(false);
 const plan=result.plans[selected]||result.plans[0];
 const update=(key:keyof Constraints,value:unknown)=>{setC(s=>({...s,[key]:value}));setDirty(true);};
 async function api<T>(body:unknown){const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as T & {error?:string};if(!r.ok)throw Error(data.error||'Please try again.');return data;}
 async function extract(){setBusy('extract');setError('');try{const data=await api<{constraints:Constraints;notes:string}>({action:'extract',message,constraints:c});setC(data.constraints);setNotice(`GPT-4.1 understood your request. ${data.notes}`);setDirty(true);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function build(){setBusy('plan');setError('');try{setResult(await api<Result>({action:'plan',constraints:c}));setSelected(0);setExplanation('');setChecked([]);setDirty(false);setNotice('Plan updated. All totals are calculated from whole packs and return journeys.');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function explain(){setBusy('explain');setError('');try{const data=await api<{explanation:string}>({action:'explain',constraints:result.constraints,planId:plan?.id});setExplanation(data.explanation);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 function download(){if(!plan)return;const text=`DublinSaver — illustrative dinner plan\n${result.constraints.location} · until ${result.constraints.endDate}\nBudget: ${money(result.constraints.budget*100)}\nGroceries: ${money(plan.groceries)}\nTransport: ${money(plan.transport)}\nOptional meal: ${money(plan.meal)}\nRemaining: ${money(plan.remaining)} (includes ${money(plan.reserve)} protected buffer)\n\nShopping list\n${plan.basket.map(p=>`${p.quantity} × ${p.name} (${p.pack}) — ${money(p.total)}`).join('\n')}\n\nDinners\n${plan.dinners.map(p=>`Day ${p.day}: ${p.name}`).join('\n')}\n\n${result.notice}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='dublinsaver-plan.txt';a.click();URL.revokeObjectURL(url);}
 return <main><header><a className="brand" href="/" aria-label="DublinSaver home"><span className="brand-icon"><Wallet size={22}/></span>Dublin<span>Saver</span></a><div className="header-right"><span className="location"><MapPin size={15}/> Dublin, Ireland</span><span className="prototype">Working prototype</span><span className="avatar">A</span></div></header>
 <div className="workspace"><section className="intro"><div><div className="eyebrow">A LITTLE CLARITY. A LITTLE MORE LEFT.</div><h1>Make your remaining<br/>money last longer<span>.</span></h1><p>A plan for the money you still have — and the life you need to live.</p></div><div className="intro-note"><Leaf size={21}/><span>Food on the table.<br/>A way to get there.<br/><strong>Room to breathe.</strong></span></div></section>
 <div className="main-grid"><aside><section className="card input-card"><div className="section-title"><span className="step">01</span><h2>Start with what you have</h2></div><label className="message-label" htmlFor="message">Tell us what your week looks like</label><textarea id="message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={1500}/><button className="ai-button" disabled={!!busy} onClick={extract}><Sparkles size={17}/>{busy==='extract'?'Understanding your week…':'Understand with AI'}</button><p className="micro">Your message is sent securely to Azure GPT-4.1.</p><div className="divider"/><div className="detail-heading"><SlidersHorizontal size={17}/><h3>Check your details</h3><span>Editable</span></div><div className="fields"><label>Money available (€)<input type="number" min="0" max="1000" step="0.01" value={c.budget} onChange={e=>update('budget',Number(e.target.value))}/></label><label>Lasts until<input value={c.endDate} maxLength={40} onChange={e=>update('endDate',e.target.value)}/></label><label>Dinners needed<input type="number" min="1" max="14" value={c.dinners} onChange={e=>update('dinners',Number(e.target.value))}/></label><label>College days<input type="number" min="0" max="14" value={c.collegeDays} onChange={e=>update('collegeDays',Number(e.target.value))}/></label><label>Food preference<select value={c.diet} onChange={e=>update('diet',e.target.value)}><option value="vegetarian">Vegetarian</option><option value="vegan">Vegan</option><option value="any">No preference</option></select></label><label>Area<input value={c.location} maxLength={80} onChange={e=>update('location',e.target.value)}/></label></div><details><summary>Travel & buffer settings <ChevronDown size={15}/></summary><div className="fields advanced"><label>Single fare (€)<input type="number" min="0" max="20" step="0.1" value={c.fare} onChange={e=>update('fare',Number(e.target.value))}/></label><label>Keep back (€)<input type="number" min="0" step="0.5" value={c.buffer} onChange={e=>update('buffer',Number(e.target.value))}/></label><label>Max shop walk (min)<input type="number" min="0" max="60" value={c.maxWalk} onChange={e=>update('maxWalk',Number(e.target.value))}/></label></div><p className="micro">Sample fare; enter your verified fare. Two paid journeys per college day. Shop walks are illustrative, not route estimates.</p><label className="checkbox"><input type="checkbox" checked={c.optionalMeal} onChange={e=>update('optionalMeal',e.target.checked)}/>Include a €5 optional meal allowance</label></details><button className="primary" disabled={!!busy} onClick={build}>{busy==='plan'?'Finding a feasible plan…':'Build my plan'}<Sparkles size={17}/></button></section><div className="aside-note"><Info size={18}/><p>One budget. Everything connected.<br/><span>Food and travel choices, considered together.</span></p></div></aside>
 <section className="results" aria-live="polite">{error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert">{notice}</div>}{dirty&&<div className="alert">Your details changed. Build your plan to update the results below.</div>}<div className="result-heading"><div className="section-title"><span className="step">02</span><h2>Your week, within reach</h2></div><span className="sample-tag">Sample prices</span></div>
 {plan?<><section className="budget-card"><div><div className="budget-label">YOUR {money(result.constraints.budget*100)} PLAN</div><h2>{result.constraints.dinners} dinners. {result.constraints.collegeDays} college days.<br/>You can make this work.</h2><div className="budget-status"><CircleCheck size={16}/> Essentials covered in this sample plan</div></div><div className="remaining"><span>Money left</span><strong>{money(plan.remaining)}</strong><span>Includes {money(plan.reserve)} protected buffer</span></div><div className="budget-bar" aria-label="Budget allocation">{[{v:plan.groceries,c:'grocery'},{v:plan.transport,c:'transport'},{v:plan.meal,c:'meal'},{v:plan.remaining,c:'left'}].map(x=><div key={x.c} className={x.c} style={{width:`${x.v/(result.constraints.budget*100)*100}%`}}/>)}</div><div className="budget-legend"><span><i className="grocery"/>Groceries</span><span><i className="transport"/>Transport</span>{plan.meal>0&&<span><i className="meal"/>Optional meal</span>}<span><i className="left"/>Left over</span></div></section>
 <div className="stats"><div><ShoppingBasket/><span>Grocery basket</span><strong>{money(plan.groceries)}</strong><small>{plan.basket.reduce((s,p)=>s+p.quantity,0)} whole packs</small></div><div><Bus/><span>Transport reserved</span><strong>{money(plan.transport)}</strong><small>{result.constraints.collegeDays*2} journeys × {money(result.constraints.fare*100)}</small></div><div><Utensils/><span>Optional meal</span><strong>{money(plan.meal)}</strong><small>{plan.meal?'Allowance, not a booking':'Not included in this plan'}</small></div></div>
 <div className="compare-heading"><h3>Choose your balance</h3><span>{result.evaluated} combinations checked</span></div><div className="plan-options">{result.plans.slice(0,3).map((p,i)=><button key={p.id} className={selected===i?'plan-option selected':'plan-option'} onClick={()=>{setSelected(i);setChecked([]);setExplanation('');}}><span className="option-top">{i===0?'Recommended':p.shop==='Nearby shop'?'Closer to home':'Another option'}{selected===i&&<CircleCheck size={16}/>}</span><strong>{money(p.total)}<small> total spend</small></strong><span><Clock size={13}/>{p.walk}-min sample walk · {p.style==='variety'?'3':'2'}-dish rotation</span></button>)}</div>
 <section className="card detail-card"><div className="tabs"><button className={tab==='basket'?'active':''} onClick={()=>setTab('basket')}><ShoppingBasket size={17}/>Shopping list</button><button className={tab==='meals'?'active':''} onClick={()=>setTab('meals')}><Utensils size={17}/>Dinner plan</button><button className="download" aria-label="Download plan" onClick={download}><Download size={18}/></button></div>{tab==='basket'?<><div className="list-subtitle"><span>{plan.shop} · illustrative basket</span><span>Whole-pack prices</span></div><div className="shopping-list">{plan.basket.map(p=><label key={p.id} className={checked.includes(p.id)?'shopping-row done':'shopping-row'}><input type="checkbox" checked={checked.includes(p.id)} onChange={()=>setChecked(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}/><span><strong>{p.name}</strong><small>{p.quantity} × {p.pack}</small></span><b>{money(p.total)}</b></label>)}</div><div className="basket-total"><span>Basket total</span><strong>{money(plan.groceries)}</strong></div></>:<div className="dinner-list">{plan.dinners.map(d=><div key={d.day}><span className="day">{String(d.day).padStart(2,'0')}</span><div><strong>{d.name}</strong><small>One dinner · vegan ingredients · {d.minutes} minutes</small></div></div>)}<p className="micro">Cooking equipment and water assumed. Oil and seasoning are included in the basket. Check product labels for allergens.</p></div>}</section>
 <div className="explain-card"><Sparkles size={20}/><div><h3>Why this plan works</h3><p>{explanation||`Transport is set aside first. This basket covers ${result.constraints.dinners} dinners, with ${money(plan.remaining)} left for your buffer and other needs. Choose a different balance to trade a shorter shop walk for a different cost.`}</p><button disabled={!!busy} onClick={explain}>{busy==='explain'?'Writing your explanation…':'Explain with GPT-4.1'}<ArrowUpRight size={14}/></button></div></div></>:<section className="card no-plan"><Wallet size={36}/><h2>{result.evaluated?'This budget needs a rethink.':'No shop fits your walking limit.'}</h2><p>{result.evaluated?`The cheapest sample plan needs ${money(result.shortfall)} more to cover dinners, transport and your protected buffer. Try removing the optional meal or changing the details.`:'Increase your maximum shop walk to at least 5 minutes to compare the illustrative options.'}</p><strong>We won’t show an unaffordable plan as feasible.</strong></section>}
 <p className="disclaimer"><Info size={15}/>{result.notice}</p><div className="source-links"><a href="https://www.transportforireland.ie/fares/" target="_blank" rel="noreferrer">Check TFI fares <ArrowUpRight size={12}/></a><a href="https://www.toogoodtogo.com/en-ie" target="_blank" rel="noreferrer">Explore surplus meals <ArrowUpRight size={12}/></a></div></section></div><footer><span className="brand-small">DublinSaver</span><span>Less guessing. More living.</span><span>Built for Dublin · Prototype</span></footer></div></main>;
}
